version: '3.8'
services:
  app:
    build:
      context: ./app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/myapp_db
      MONGO_URL: mongodb://mongo:27017/
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - mongo
      - redis
      - kafka
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/init_postgres.sql:/docker-entrypoint-initdb.d/init.sql
  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
  redis:
    image: redis:6
    ports:
      - "6379:6379"
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
volumes:
  postgres_data: